apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: c1lbw69q5-dotnet-basic-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/c1lbw69q5-dotnet-basic-gitops